import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Topbar from "@/components/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="fixed top-0 w-full z-50">
            <Topbar />
            <Navbar />
          </div>
          <div className="mt-36 w-full h-screen">
            {children}
          </div>
      </body>
    </html>
  );
}
